export const BOOK_FETCH_REQUEST = 'BOOK_FETCH_REQUEST';
export const BOOK_FETCH_SUCCESS = 'BOOK_FETCH_SUCCESS';
export const BOOK_FETCH_FAILURE = 'BOOK_FETCH_FAILURE';
export const BOOK_ID = 'BOOK_ID';